/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceCard: typeof import('./src/components/ServiceCard.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UBanner: typeof import('./node_modules/@nuxt/ui-pro/dist/runtime/components/Banner.vue')['default']
    UBlogPost: typeof import('./node_modules/@nuxt/ui-pro/dist/runtime/components/BlogPost.vue')['default']
    UBlogPosts: typeof import('./node_modules/@nuxt/ui-pro/dist/runtime/components/BlogPosts.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UColorModeButton: typeof import('./node_modules/@nuxt/ui-pro/dist/runtime/vue/components/color-mode/ColorModeButton.vue')['default']
    UContainer: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UFooter: typeof import('./node_modules/@nuxt/ui-pro/dist/runtime/components/Footer.vue')['default']
    UFooterColumns: typeof import('./node_modules/@nuxt/ui-pro/dist/runtime/components/FooterColumns.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UHeader: typeof import('./node_modules/@nuxt/ui-pro/dist/runtime/components/Header.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UNavigationMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPage: typeof import('./node_modules/@nuxt/ui-pro/dist/runtime/components/Page.vue')['default']
    UPageAccordion: typeof import('./node_modules/@nuxt/ui-pro/dist/runtime/components/PageAccordion.vue')['default']
    UPageCard: typeof import('./node_modules/@nuxt/ui-pro/dist/runtime/components/PageCard.vue')['default']
    UPageCTA: typeof import('./node_modules/@nuxt/ui-pro/dist/runtime/components/PageCTA.vue')['default']
    UPageFeature: typeof import('./node_modules/@nuxt/ui-pro/dist/runtime/components/PageFeature.vue')['default']
    UPageGrid: typeof import('./node_modules/@nuxt/ui-pro/dist/runtime/components/PageGrid.vue')['default']
    UPageHero: typeof import('./node_modules/@nuxt/ui-pro/dist/runtime/components/PageHero.vue')['default']
    UPageMarquee: typeof import('./node_modules/@nuxt/ui-pro/dist/runtime/components/PageMarquee.vue')['default']
    UPageSection: typeof import('./node_modules/@nuxt/ui-pro/dist/runtime/components/PageSection.vue')['default']
    USkeleton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    UStepper: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Stepper.vue')['default']
    UTextarea: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTimeline: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Timeline.vue')['default']
    UUser: typeof import('./node_modules/@nuxt/ui-pro/dist/runtime/components/User.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
    WestMidlandsMap: typeof import('./src/components/WestMidlandsMap.vue')['default']
  }
}
